# Generated by Django 3.2.4 on 2021-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(upload_to='static/img', verbose_name='Fotografía'),
        ),
    ]
