# Generated by Django 3.2.4 on 2021-07-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosnews', '0002_alter_colaborador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(upload_to='subidas/img/', verbose_name='Fotografía'),
        ),
    ]
